exclude: README.md, .gitignore
permalink: '/:year/:month/:title' 
description: 'Blog of the Cape Town Node.js user group'
baseurl: http://adrianrossouw.github.com/nodecpt/
twitter_search: 'nodecpt OR #nodecpt OR @nodecpt -from:Nodejs_bot'
siteName: 'Node Cape Town'
paginate: 3
hashtag: '#nodecpt'
github_login: 'nodecpt'
github_repo: 'nodecpt.github.com'
github_language: 'JavaScript'
