auto: true
server: true
exclude: README.md, .gitignore
permalink: '/:year/:month/:title' 
description: 'Blog of the Cape Town Node.js user group'
baseurl: http://nodecpt.github.com/
twitter_search: '#nodecpt OR @nodecpt -from:Nodejs_bot'
siteName: 'Node Cape Town'
hashtag: '#nodecpt'
github_login: 'nodecpt'
github_repo: 'nodecpt.github.com'
github_language: 'JavaScript'
